[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

# This plugin is essential for Next.js to work on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Standard build settings

[[redirects]]
  from = "/api/*"
  to = "https://graviton-backend.onrender.com/api/:splat"
  status = 200
  force = true
